[package]
name = "slog_stats"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
fb_stats = { path = "../stats" }
slog = { version = "2.5", features = ["max_level_debug"] }
