[package]
name = "futures_stats"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/**/*.rs", "test/**/*.rs"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "futures_stats_test"
path = "test/main.rs"

[dependencies]
fb_futures_ext = { path = "../futures_ext" }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
tokio-old = { package = "tokio", version = "0.1" }

[dev-dependencies]
anyhow = "1.0"
tokio = { version = "=0.2.13", features = ["full"] }
tokio-timer = "0.2"
