[package]
name = "sql_common"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
cloned = { path = "../../cloned" }
fb_failure_ext = { path = "../../failure_ext" }
futures_ext = { path = "../../futures_ext" }
mysql_derive = { path = "../derive" }
anyhow = "1.0"
auto_impl = "0.4"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
futures-util = "0.3"
lazy_static = "1.0"
mysql_async = { version = "0.23" }
rusqlite = { version = "0.23", features = ["blob", "bundled"] }
thiserror = "1.0"

[dev-dependencies]
sql = { path = ".." }
sql_tests_lib = { path = "../tests_lib" }
