[package]
name = "fbthrift_codegen_includer_proc_macro"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
build = "build.rs"
include = ["src/**/*.rs", "tests/**/*.rs"]

[lib]
name = "codegen_includer_proc_macro"
path = "src/lib.rs"
proc-macro = true
test = false
doctest = false

[[test]]
name = "tests"
path = "tests/main.rs"

[dependencies]
quote = "1.0"
